/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package root.gestionagricola.vistas;

import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import root.gestionagricola.gestionusuario.ControladorUsuario;

/**
 *
 * @author ignacioburgos
 */
public class ModificarDatoCuentaPropia extends javax.swing.JFrame {

    
    public ModificarDatoCuentaPropia() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        RespuestaContrasenaAntigua = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        RespuestaContrasena = new javax.swing.JTextField();
        modificar = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Garamond", 1, 14)); // NOI18N
        jLabel2.setText("Contraseña Antigua:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 50, 130, -1));

        RespuestaContrasenaAntigua.setFont(new java.awt.Font("Garamond", 1, 14)); // NOI18N
        jPanel1.add(RespuestaContrasenaAntigua, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 50, 185, -1));

        jLabel6.setBackground(new java.awt.Color(255, 255, 255));
        jLabel6.setFont(new java.awt.Font("Garamond", 1, 14)); // NOI18N
        jLabel6.setText("Contraseña Nueva:");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 110, 130, -1));

        RespuestaContrasena.setFont(new java.awt.Font("Garamond", 1, 14)); // NOI18N
        jPanel1.add(RespuestaContrasena, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 110, 185, -1));

        modificar.setFont(new java.awt.Font("Garamond", 1, 14)); // NOI18N
        modificar.setText("Modificar");
        modificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modificarActionPerformed(evt);
            }
        });
        jPanel1.add(modificar, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 180, 135, -1));

        jButton2.setFont(new java.awt.Font("Garamond", 1, 14)); // NOI18N
        jButton2.setText("Cancelar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 180, 135, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 615, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void modificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modificarActionPerformed
    
        if(this.RespuestaContrasenaAntigua != null && this.RespuestaContrasena != null){

            try {   
                boolean datos = ControladorUsuario.BuscarContrasena(this.getName(), this.RespuestaContrasenaAntigua.getText());
                if(datos == true){
                    ControladorUsuario.ModificarContrasena(this.getName(), this.RespuestaContrasena.getText());
                    this.dispose();
                    JOptionPane.showMessageDialog(null, "Contraseña Modificada.", "Modificación Contraseña", JOptionPane.INFORMATION_MESSAGE);
                }
                else{
                    this.dispose();
                    JOptionPane.showMessageDialog(null, "La contraseña actual no es igual.", "Modificación Contraseña", JOptionPane.INFORMATION_MESSAGE);
                    
                }
            } catch (ClassNotFoundException ex) {
                Logger.getLogger(ModificarDatoCuentaPropia.class.getName()).log(Level.SEVERE, null, ex);
            } catch (IllegalAccessException ex) {
                Logger.getLogger(ModificarDatoCuentaPropia.class.getName()).log(Level.SEVERE, null, ex);
            } catch (InstantiationException ex) {
                Logger.getLogger(ModificarDatoCuentaPropia.class.getName()).log(Level.SEVERE, null, ex);
            } catch (SQLException ex) {
                Logger.getLogger(ModificarDatoCuentaPropia.class.getName()).log(Level.SEVERE, null, ex);
            }
        }else{
            JOptionPane.showMessageDialog(null, "Faltan llenar casillas.", "ERROR", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_modificarActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

  
    public JTextField getRespuestaContrasena() {
        return RespuestaContrasena;
    }

    public void setRespuestaContrasena(JTextField RespuestaContrasena) {
        this.RespuestaContrasena = RespuestaContrasena;
    }

    public JTextField getRespuestaNombreUsuario() {
        return RespuestaContrasenaAntigua;
    }

    public void setRespuestaNombreUsuario(JTextField RespuestaNombreUsuario) {
        this.RespuestaContrasenaAntigua = RespuestaNombreUsuario;
    }

   

    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField RespuestaContrasena;
    private javax.swing.JTextField RespuestaContrasenaAntigua;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton modificar;
    // End of variables declaration//GEN-END:variables
}
