/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package root.gestionagricola.vistas;

/**
 *
 * @author ignacioburgos
 */
public class VistaRegistro extends javax.swing.JFrame {

    /**
     * Creates new form VistaRegistro
     */
    public VistaRegistro() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        Titulo10 = new javax.swing.JLabel();
        Titulo7 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        Titulo8 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        Titulo11 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        Titulo13 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        Titulo14 = new javax.swing.JLabel();
        Titulo1 = new javax.swing.JLabel();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jRadioButton3 = new javax.swing.JRadioButton();
        jPanel4 = new javax.swing.JPanel();
        Titulo9 = new javax.swing.JLabel();
        Titulo15 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(25, 25, 112));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(80, 214, 141));

        Titulo10.setBackground(new java.awt.Color(255, 255, 255));
        Titulo10.setFont(new java.awt.Font("Arial", 0, 48)); // NOI18N
        Titulo10.setForeground(new java.awt.Color(255, 255, 255));
        Titulo10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Titulo10.setText("Iniciar Sesión");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(81, 81, 81)
                .addComponent(Titulo10, javax.swing.GroupLayout.PREFERRED_SIZE, 397, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(172, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(Titulo10, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 650, 120));

        Titulo7.setBackground(new java.awt.Color(255, 255, 255));
        Titulo7.setFont(new java.awt.Font("Arial", 0, 36)); // NOI18N
        Titulo7.setForeground(new java.awt.Color(255, 255, 255));
        Titulo7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Titulo7.setText("Nombre: ");
        jPanel1.add(Titulo7, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 270, 160, 40));
        jPanel1.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 270, 410, 50));

        Titulo8.setBackground(new java.awt.Color(255, 255, 255));
        Titulo8.setFont(new java.awt.Font("Arial", 0, 36)); // NOI18N
        Titulo8.setForeground(new java.awt.Color(255, 255, 255));
        Titulo8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Titulo8.setText("Apellido:");
        jPanel1.add(Titulo8, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 340, 170, 40));
        jPanel1.add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 330, 410, 50));

        Titulo11.setBackground(new java.awt.Color(255, 255, 255));
        Titulo11.setFont(new java.awt.Font("Arial", 0, 36)); // NOI18N
        Titulo11.setForeground(new java.awt.Color(255, 255, 255));
        Titulo11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Titulo11.setText("Correo:");
        jPanel1.add(Titulo11, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 400, 200, 40));
        jPanel1.add(jTextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 390, 410, 50));

        Titulo13.setBackground(new java.awt.Color(255, 255, 255));
        Titulo13.setFont(new java.awt.Font("Arial", 0, 36)); // NOI18N
        Titulo13.setForeground(new java.awt.Color(255, 255, 255));
        Titulo13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Titulo13.setText("Cargo:");
        jPanel1.add(Titulo13, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 460, 220, 40));

        jButton1.setFont(new java.awt.Font("Arial Black", 1, 24)); // NOI18N
        jButton1.setText("Registrarse");
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 560, 280, 60));

        Titulo14.setBackground(new java.awt.Color(255, 255, 255));
        Titulo14.setFont(new java.awt.Font("Arial", 0, 36)); // NOI18N
        Titulo14.setForeground(new java.awt.Color(241, 196, 15));
        Titulo14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel1.add(Titulo14, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 690, 1270, 70));

        Titulo1.setBackground(new java.awt.Color(255, 255, 255));
        Titulo1.setFont(new java.awt.Font("Arial Black", 1, 36)); // NOI18N
        Titulo1.setForeground(new java.awt.Color(255, 255, 255));
        Titulo1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Titulo1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/frutap.png"))); // NOI18N
        Titulo1.setText("LOG IN  ");
        jPanel1.add(Titulo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 120, 240, 160));

        jRadioButton1.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jRadioButton1.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButton1.setText("Dueño");
        jPanel1.add(jRadioButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 470, -1, 40));

        jRadioButton2.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jRadioButton2.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButton2.setText("Supervisor");
        jPanel1.add(jRadioButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 470, -1, -1));

        jRadioButton3.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jRadioButton3.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButton3.setText("Administrador");
        jPanel1.add(jRadioButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 470, -1, -1));

        jPanel4.setBackground(new java.awt.Color(39, 119, 20));

        Titulo9.setBackground(new java.awt.Color(255, 255, 255));
        Titulo9.setFont(new java.awt.Font("Arial", 0, 48)); // NOI18N
        Titulo9.setForeground(new java.awt.Color(255, 255, 255));
        Titulo9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Titulo9.setText("Registrarse");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(119, Short.MAX_VALUE)
                .addComponent(Titulo9, javax.swing.GroupLayout.PREFERRED_SIZE, 397, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(104, 104, 104))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(Titulo9, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 0, 620, 120));

        Titulo15.setBackground(new java.awt.Color(255, 255, 255));
        Titulo15.setFont(new java.awt.Font("Arial", 0, 36)); // NOI18N
        Titulo15.setForeground(new java.awt.Color(241, 196, 15));
        Titulo15.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel1.add(Titulo15, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 690, 1220, 70));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VistaRegistro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VistaRegistro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VistaRegistro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VistaRegistro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VistaRegistro().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Titulo1;
    private javax.swing.JLabel Titulo10;
    private javax.swing.JLabel Titulo11;
    private javax.swing.JLabel Titulo13;
    private javax.swing.JLabel Titulo14;
    private javax.swing.JLabel Titulo15;
    private javax.swing.JLabel Titulo7;
    private javax.swing.JLabel Titulo8;
    private javax.swing.JLabel Titulo9;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JRadioButton jRadioButton3;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    // End of variables declaration//GEN-END:variables
}
