package root.gestionagricola.vistas.dueño;

import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import root.gestionagricola.gestiontrabajador.ControladorTrabajador;

/**
 *
 * @author Ronaru
 */
public class EliminarTrabajadorInterno extends javax.swing.JFrame {
    GestionTrabajadorInterno gestion;
    
    public EliminarTrabajadorInterno(GestionTrabajadorInterno gestion) {
        this.gestion = gestion;
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the FormEditor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        botonEliminar = new javax.swing.JButton();
        botonCancelar = new javax.swing.JButton();
        datoRut_Trabajador = new javax.swing.JTextField();
        etiquetaRut_Trabajador = new javax.swing.JLabel();

        setLayout(new java.awt.BorderLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        botonEliminar.setBackground(new java.awt.Color(255, 255, 255));
        botonEliminar.setFont(new java.awt.Font("Garamond", 1, 14)); // NOI18N
        botonEliminar.setText("Eliminar");
        botonEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonEliminarActionPerformed(evt);
            }
        });
        jPanel1.add(botonEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 240, -1, -1));

        botonCancelar.setBackground(new java.awt.Color(255, 255, 255));
        botonCancelar.setFont(new java.awt.Font("Garamond", 1, 14)); // NOI18N
        botonCancelar.setText("Cancelar");
        botonCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonCancelarActionPerformed(evt);
            }
        });
        jPanel1.add(botonCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 240, -1, -1));

        datoRut_Trabajador.setFont(new java.awt.Font("Garamond", 0, 14)); // NOI18N
        datoRut_Trabajador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                datoRut_TrabajadorActionPerformed(evt);
            }
        });
        jPanel1.add(datoRut_Trabajador, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 120, 220, -1));

        etiquetaRut_Trabajador.setBackground(new java.awt.Color(255, 255, 255));
        etiquetaRut_Trabajador.setFont(new java.awt.Font("Garamond", 1, 14)); // NOI18N
        etiquetaRut_Trabajador.setText("Ingrese el Rut del Trabajador");
        jPanel1.add(etiquetaRut_Trabajador, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 120, -1, -1));

        add(jPanel1, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void datoRut_TrabajadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_datoRut_TrabajadorActionPerformed
        
    }//GEN-LAST:event_datoRut_TrabajadorActionPerformed

    private void botonCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonCancelarActionPerformed
       this.dispose();
    }//GEN-LAST:event_botonCancelarActionPerformed

    private void botonEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonEliminarActionPerformed
        // este boton es cuando apreta Eliminar.
        if(this.datoRut_Trabajador.getText() != null){
            // aqui se llama al método controlador que hara la conexion con el modelo.
            //ControladorTrabajador.
             try {
                String[][] datos;
                datos = ControladorTrabajador.cargarDatos();
                gestion.setDatos_para_tabla(datos);
                gestion.cargarDatosTabla();
                
            } catch (ClassNotFoundException ex) {
                Logger.getLogger(CrearTrabajadorInterno.class.getName()).log(Level.SEVERE, null, ex);
            } catch (InstantiationException ex) {
                Logger.getLogger(CrearTrabajadorInterno.class.getName()).log(Level.SEVERE, null, ex);
            } catch (IllegalAccessException ex) {
                Logger.getLogger(CrearTrabajadorInterno.class.getName()).log(Level.SEVERE, null, ex);
            } catch (SQLException ex) {
                Logger.getLogger(CrearTrabajadorInterno.class.getName()).log(Level.SEVERE, null, ex);
            }
            this.dispose();
            JOptionPane.showMessageDialog(null, "Cuenta de trabajador Eliminada.", "Eliminar", JOptionPane.INFORMATION_MESSAGE);
        }
        else{ //si no le avisa al usuario que le faltan casillas por llenar.
            JOptionPane.showMessageDialog(null, "No se han introducido datos", "ERROR", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_botonEliminarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonCancelar;
    private javax.swing.JButton botonEliminar;
    private javax.swing.JTextField datoRut_Trabajador;
    private javax.swing.JLabel etiquetaRut_Trabajador;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
