
package root.gestionagricola.vistas.administrador;

import javax.swing.JComboBox;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import root.gestionagricola.gestionusuario.ControladorUsuario;

/**
 * Vista para crear usuarios.
 * @author Los Lanzas
 */
public class crearDatosUsuario extends javax.swing.JFrame {

    Administrador admin;

    /**
     * Constructor de la vista
     * @param admin
     */
    public crearDatosUsuario(Administrador admin) {
        this.admin = admin;
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        RespuestaNombre = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        RespuestaContrasena = new javax.swing.JTextField();
        CrearUsuario = new javax.swing.JButton();
        CancelarUsuario = new javax.swing.JButton();
        RespuestaTipo = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Garamond", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Nombre Usuario:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 50, 130, -1));

        RespuestaNombre.setFont(new java.awt.Font("Garamond", 1, 14)); // NOI18N
        RespuestaNombre.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.add(RespuestaNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 50, 185, -1));

        jLabel6.setBackground(new java.awt.Color(255, 255, 255));
        jLabel6.setFont(new java.awt.Font("Garamond", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setText("Contraseña:");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 120, 100, -1));

        RespuestaContrasena.setFont(new java.awt.Font("Garamond", 1, 14)); // NOI18N
        RespuestaContrasena.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.add(RespuestaContrasena, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 110, 185, -1));

        CrearUsuario.setFont(new java.awt.Font("Garamond", 1, 14)); // NOI18N
        CrearUsuario.setText("Crear");
        CrearUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CrearUsuarioActionPerformed(evt);
            }
        });
        jPanel1.add(CrearUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 280, 135, -1));

        CancelarUsuario.setFont(new java.awt.Font("Garamond", 1, 14)); // NOI18N
        CancelarUsuario.setText("Cancelar");
        CancelarUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CancelarUsuarioActionPerformed(evt);
            }
        });
        jPanel1.add(CancelarUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 280, 135, -1));

        RespuestaTipo.setForeground(new java.awt.Color(0, 0, 0));
        RespuestaTipo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Administrador", "Dueño", "Supervisor" }));
        RespuestaTipo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RespuestaTipoActionPerformed(evt);
            }
        });
        jPanel1.add(RespuestaTipo, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 200, 185, 21));

        jLabel9.setBackground(new java.awt.Color(255, 255, 255));
        jLabel9.setFont(new java.awt.Font("Garamond", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 0, 0));
        jLabel9.setText("Tipo de Cuenta:");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 200, 120, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 615, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CrearUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CrearUsuarioActionPerformed
        //Si las casillas estan llenas puede guardar los datos
        if (this.RespuestaNombre.getText() != null && this.RespuestaContrasena.getText() != null && this.RespuestaTipo.getSelectedItem() != null){
            // aqui se llama al método controlador que hara la conexion con el modelo.
            ControladorUsuario.CrearUsuario(this.RespuestaNombre.getText(), this.RespuestaContrasena.getText(),(String)this.RespuestaTipo.getSelectedItem());
            
            String[][] datos;
            datos = ControladorUsuario.cargarDatos();
            admin.setDatos_para_tabla(datos);
            admin.cargarDatosTabla();
            
            this.dispose();
            JOptionPane.showMessageDialog(null, "Cuenta de Usuario Ingresada.", "Creación", JOptionPane.INFORMATION_MESSAGE);
        }
        else{//si no le avisa al usuario que le faltan casillas por llenar.
            JOptionPane.showMessageDialog(null, "Faltan llenar casillas.", "ERROR", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_CrearUsuarioActionPerformed

    private void CancelarUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CancelarUsuarioActionPerformed
        this.dispose();
    }//GEN-LAST:event_CancelarUsuarioActionPerformed

    private void RespuestaTipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RespuestaTipoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RespuestaTipoActionPerformed

    /**
     * Permite obtener la contraseña
     * @return
     */
    public JTextField getRespuestaContrasena() {
        return RespuestaContrasena;
    }

    /**
     * Permite setear la contraseña
     * @param RespuestaContrasena
     */
    public void setRespuestaContrasena(JTextField RespuestaContrasena) {
        this.RespuestaContrasena = RespuestaContrasena;
    }

    /**
     * Permite obtener el nombre
     * @return
     */
    public JTextField getRespuestaNombre() {
        return RespuestaNombre;
    }

    /**
     * Permite setear el nombre.
     * @param RespuestaNombre
     */
    public void setRespuestaNombre(JTextField RespuestaNombre) {
        this.RespuestaNombre = RespuestaNombre;
    }

    /**
     * Permite obtener tipo.
     * @return
     */
    public JComboBox<String> getRespuestaTipo() {
        return RespuestaTipo;
    }

    /**
     * Permite setear tipo.
     * @param RespuestaTipo
     */
    public void setRespuestaTipo(JComboBox<String> RespuestaTipo) {
        this.RespuestaTipo = RespuestaTipo;
    }

    
    
    
    
    
    
    
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CancelarUsuario;
    private javax.swing.JButton CrearUsuario;
    private javax.swing.JTextField RespuestaContrasena;
    private javax.swing.JTextField RespuestaNombre;
    private javax.swing.JComboBox<String> RespuestaTipo;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
