/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package root.gestionagricola.vistas.administrador;

import javax.swing.JComboBox;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import root.gestionagricola.gestionusuario.ControladorUsuario;

/**
 *
 * @author ignacioburgos
 */
public class EliminarDatoUsuario extends javax.swing.JFrame {

    private String nombre_recibido;
    private String contrasena_recibido;
    
    public EliminarDatoUsuario() {
        initComponents();
        this.setLocationRelativeTo(null);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        RespuestaNombreUsuario = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        RespuestaContrasena = new javax.swing.JTextField();
        BotonEliminar = new javax.swing.JButton();
        Cancelar = new javax.swing.JButton();
        RespuestEstado = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Garamond", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Nombre Usuario:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 50, 130, -1));

        RespuestaNombreUsuario.setFont(new java.awt.Font("Garamond", 1, 14)); // NOI18N
        RespuestaNombreUsuario.setForeground(new java.awt.Color(0, 0, 0));
        RespuestaNombreUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RespuestaNombreUsuarioActionPerformed(evt);
            }
        });
        jPanel1.add(RespuestaNombreUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 50, 185, -1));

        jLabel6.setBackground(new java.awt.Color(255, 255, 255));
        jLabel6.setFont(new java.awt.Font("Garamond", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setText("Contraseña:");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 120, 100, -1));

        RespuestaContrasena.setFont(new java.awt.Font("Garamond", 1, 14)); // NOI18N
        RespuestaContrasena.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.add(RespuestaContrasena, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 110, 185, -1));

        BotonEliminar.setFont(new java.awt.Font("Garamond", 1, 14)); // NOI18N
        BotonEliminar.setText("Eliminar");
        BotonEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonEliminarActionPerformed(evt);
            }
        });
        jPanel1.add(BotonEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 260, 135, -1));

        Cancelar.setFont(new java.awt.Font("Garamond", 1, 14)); // NOI18N
        Cancelar.setText("Cancelar");
        Cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CancelarActionPerformed(evt);
            }
        });
        jPanel1.add(Cancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 260, 135, -1));

        RespuestEstado.setForeground(new java.awt.Color(0, 0, 0));
        RespuestEstado.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Administrador", "Dueño", "Supervisor" }));
        RespuestEstado.setEnabled(false);
        RespuestEstado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RespuestEstadoActionPerformed(evt);
            }
        });
        jPanel1.add(RespuestEstado, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 200, 185, 21));

        jLabel9.setBackground(new java.awt.Color(255, 255, 255));
        jLabel9.setFont(new java.awt.Font("Garamond", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 0, 0));
        jLabel9.setText("Tipo de Cuenta:");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 200, 120, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 615, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BotonEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonEliminarActionPerformed

        // este boton es cuando apreta Eliminar.
        /*String[] datos = null;
        datos = ControladorUsuario.getUsuario(this.nombre_recibido, this.contrasena_recibido);
        if(datos == null){
            JOptionPane.showMessageDialog(null, "El usuario a eliminar no existe.", "ERROR", JOptionPane.WARNING_MESSAGE);
        }else{
            this.RespuestaNombreUsuario.setText(datos[0]);
            this.RespuestaContrasena.setText(datos[1]);
            JOptionPane.showMessageDialog(null, "Usuario Eliminado.", "ERROR", JOptionPane.INFORMATION_MESSAGE);
        }*/
        
        // este boton es cuando apreta Eliminar.
        if(this.RespuestaNombreUsuario.getText() != null && this.RespuestaContrasena != null){
            // aqui se llama al método controlador que hara la conexion con el modelo.
            ControladorUsuario.EliminarUsuario(this.RespuestaNombreUsuario.getText(), this.RespuestaContrasena.getText());
            this.dispose();
        }
        else{ //si no le avisa al usuario que le faltan casillas por llenar.
            JOptionPane.showMessageDialog(null, "Faltan llenar casillas.", "ERROR", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_BotonEliminarActionPerformed

    private void CancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CancelarActionPerformed
        this.dispose();
    }//GEN-LAST:event_CancelarActionPerformed

    private void RespuestEstadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RespuestEstadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RespuestEstadoActionPerformed

    private void RespuestaNombreUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RespuestaNombreUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RespuestaNombreUsuarioActionPerformed

    public String getNombre_recibido() {
        return nombre_recibido;
    }

    public void setNombre_recibido(String nombre_recibido) {
        this.nombre_recibido = nombre_recibido;
    }

    public JTextField getRespuestaContrasena() {
        return RespuestaContrasena;
    }

    public void setRespuestaContrasena(JTextField RespuestaContrasena) {
        this.RespuestaContrasena = RespuestaContrasena;
    }

    public String getContrasena_recibido() {
        return contrasena_recibido;
    }

    public void setContrasena_recibido(String contrasena_recibido) {
        this.contrasena_recibido = contrasena_recibido;
    }
        
    public JComboBox<String> getRespuestEstado() {
        return RespuestEstado;
    }




    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotonEliminar;
    private javax.swing.JButton Cancelar;
    private javax.swing.JComboBox<String> RespuestEstado;
    private javax.swing.JTextField RespuestaContrasena;
    private javax.swing.JTextField RespuestaNombreUsuario;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
