/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package root.gestionagricola.vistas.administrador;

import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import root.gestionagricola.gestionusuario.ControladorUsuario;
import root.gestionagricola.vistas.ControladorVistas;

/**
 *
 * @author ignacioburgos
 */
public class ModificarDatoUsuario extends javax.swing.JFrame {

    private String nombre_recibido;
    private String contrasena_recibido;
    private Administrador admin;
    
    public ModificarDatoUsuario(Administrador admin) {
        this.admin = admin;
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        RespuestaNombreUsuarioNuevo = new javax.swing.JTextField();
        modificar = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        RespuestaEstado = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        RespuestaNombreUsuario = new javax.swing.JTextField();
        GenerarContraseña = new javax.swing.JButton();
        RespuestaContrasena = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Garamond", 1, 14)); // NOI18N
        jLabel2.setText("Nombre Usuario Nuevo:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 80, 170, -1));

        RespuestaNombreUsuarioNuevo.setFont(new java.awt.Font("Garamond", 1, 14)); // NOI18N
        jPanel1.add(RespuestaNombreUsuarioNuevo, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 80, 185, -1));

        modificar.setFont(new java.awt.Font("Garamond", 1, 14)); // NOI18N
        modificar.setText("Modificar");
        modificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modificarActionPerformed(evt);
            }
        });
        jPanel1.add(modificar, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 280, 140, -1));

        jButton2.setFont(new java.awt.Font("Garamond", 1, 14)); // NOI18N
        jButton2.setText("Cancelar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 280, 135, -1));

        RespuestaEstado.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Administrador", "Dueño", "Supervisor" }));
        RespuestaEstado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RespuestaEstadoActionPerformed(evt);
            }
        });
        jPanel1.add(RespuestaEstado, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 130, 185, 21));

        jLabel9.setBackground(new java.awt.Color(255, 255, 255));
        jLabel9.setFont(new java.awt.Font("Garamond", 1, 14)); // NOI18N
        jLabel9.setText("Tipo de Cuenta:");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 130, 120, -1));

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setFont(new java.awt.Font("Garamond", 1, 14)); // NOI18N
        jLabel3.setText("Nombre Usuario Antiguo: *");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 30, 190, -1));

        RespuestaNombreUsuario.setFont(new java.awt.Font("Garamond", 1, 14)); // NOI18N
        jPanel1.add(RespuestaNombreUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 30, 185, -1));

        GenerarContraseña.setFont(new java.awt.Font("Garamond", 1, 14)); // NOI18N
        GenerarContraseña.setText("Generar Contraseña");
        GenerarContraseña.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GenerarContraseñaActionPerformed(evt);
            }
        });
        jPanel1.add(GenerarContraseña, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 180, 160, -1));

        RespuestaContrasena.setFont(new java.awt.Font("Garamond", 1, 14)); // NOI18N
        RespuestaContrasena.setEnabled(false);
        RespuestaContrasena.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RespuestaContrasenaActionPerformed(evt);
            }
        });
        jPanel1.add(RespuestaContrasena, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 180, 185, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 615, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void modificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modificarActionPerformed
        
         // este boton es para poder modificar los datos del usuario.
        if(this.RespuestaNombreUsuario.getText() != null && this.RespuestaContrasena.getText() != null){
            try {   
               boolean BuscarUsuario = ControladorUsuario.BuscarUsuario(this.RespuestaNombreUsuario.getText());
               if(BuscarUsuario == true){
                    if(this.RespuestaNombreUsuarioNuevo.getText() == null){
                        ControladorUsuario.ModificarUsuario(this.RespuestaNombreUsuario.getText(), this.RespuestaNombreUsuario.getText(), this.RespuestaContrasena.getText(), (String)this.RespuestaEstado.getSelectedItem());
                    }
                    else if( this.RespuestaNombreUsuarioNuevo != null){
                        ControladorUsuario.ModificarUsuario(this.RespuestaNombreUsuario.getText(), this.RespuestaNombreUsuarioNuevo.getText(), this.RespuestaContrasena.getText(),(String)this.RespuestaEstado.getSelectedItem());
                    }
                    this.dispose();
                    JOptionPane.showMessageDialog(null, "Cuenta de Usuario Modificada.", "Modificación", JOptionPane.INFORMATION_MESSAGE);

                    String[][] datos;
                    datos = ControladorUsuario.cargarDatos();
                    admin.setDatos_para_tabla(datos);
                    admin.cargarDatosTabla();
               
                }
                else{
                   this.dispose();
                    JOptionPane.showMessageDialog(null, "Nombre de Usuario no encontrado.", "Modificación", JOptionPane.INFORMATION_MESSAGE);
               }

            } catch (ClassNotFoundException ex) {
               Logger.getLogger(ModificarDatoUsuario.class.getName()).log(Level.SEVERE, null, ex);
            } catch (InstantiationException ex) {
               Logger.getLogger(ModificarDatoUsuario.class.getName()).log(Level.SEVERE, null, ex);
            } catch (IllegalAccessException ex) {
               Logger.getLogger(ModificarDatoUsuario.class.getName()).log(Level.SEVERE, null, ex);
            } catch (SQLException ex) {
               Logger.getLogger(ModificarDatoUsuario.class.getName()).log(Level.SEVERE, null, ex);
            }
       }
       else{
            JOptionPane.showMessageDialog(null, "Faltan llenar casillas.", "ERROR", JOptionPane.WARNING_MESSAGE);
       }

    }//GEN-LAST:event_modificarActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void RespuestaEstadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RespuestaEstadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RespuestaEstadoActionPerformed

    private void GenerarContraseñaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GenerarContraseñaActionPerformed
        String contraseña = ControladorVistas.createRandomPassword();
        this.RespuestaContrasena.setText(contraseña);
    }//GEN-LAST:event_GenerarContraseñaActionPerformed

    private void RespuestaContrasenaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RespuestaContrasenaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RespuestaContrasenaActionPerformed

    public JComboBox<String> getRespuestEstado() {
        return RespuestaEstado;
    }

    public void setRespuestEstado(JComboBox<String> RespuestEstado) {
        this.RespuestaEstado = RespuestEstado;
    }

    public JTextField getRespuestaNombreUsuario() {
        return RespuestaNombreUsuarioNuevo;
    }

    public void setRespuestaNombreUsuario(JTextField RespuestaNombreUsuario) {
        this.RespuestaNombreUsuarioNuevo = RespuestaNombreUsuario;
    }

    public String getNombre_recibido() {
        return nombre_recibido;
    }

    public void setNombre_recibido(String nombre_recibido) {
        this.nombre_recibido = nombre_recibido;
    }

    public String getContrasena_recibido() {
        return contrasena_recibido;
    }

    public void setContrasena_recibido(String contrasena_recibido) {
        this.contrasena_recibido = contrasena_recibido;
    }

    public void setRespuestaContrasena(JTextField RespuestaContrasena) {
        this.RespuestaContrasena = RespuestaContrasena;
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton GenerarContraseña;
    private javax.swing.JTextField RespuestaContrasena;
    private javax.swing.JComboBox<String> RespuestaEstado;
    private javax.swing.JTextField RespuestaNombreUsuario;
    private javax.swing.JTextField RespuestaNombreUsuarioNuevo;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton modificar;
    // End of variables declaration//GEN-END:variables
}
